mesage user and account
archis-academy/July-Backend-Banking-System-1 pull request #12
Opened 2024-07-19 14:07 UTC by emre9ybar

2024-07-19 17:28 UTC, furkanErenoglu requested changes

2024-07-19 17:28 UTC, furkanErenoglu commented on src/main/java/org/example/account/CheckingAccount.java
> +public class CheckingAccount{
Burdan kaldırmalısın

2024-07-26 17:05 UTC, furkanErenoglu requested changes

2024-07-26 17:05 UTC, furkanErenoglu commented on src/main/java/org/example/messages/AccountMessage.java
> +
kayıtta bahsettiğim gibi güncellmelisin ayrıca message package ı oluşturmaya gerek yok

2024-07-29 13:12 UTC, emre9ybar commented on src/main/java/org/example/messages/AccountMessage.java
> +
nasıl oluşturalım ?

2024-08-02 14:37 UTC, emre9ybar commented
public static String FIND_ACCOUNT="Account found";
    public static String NOT_FOUND_ACCOUNT = "Account not found.";
    public static String CREATE_SUCCESS = "Account succesfully created.";
    public static String UPDATE_SUCCESS = "Account succesfully updated.";
    public static String READ_SUCCESS = "Account details retrieved successfuly";

 public static String FIND_USER = "User found.";
    public static String NOT_FOUND_USER = "User not found.";
    public static String CREATE_SUCCESS = "User successfully created.";
    public static String UPDATE_SUCCESS = "User successfully updated.";
    public static String READ_SUCCESS = "User details retrieved successfully";

2024-08-02 17:04 UTC, closed without merging